definitions:
  types.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  types.GameDefinition:
    properties:
      id:
        type: string
      libPath:
        type: string
    type: object
  types.GetAllGamesResponse:
    properties:
      games:
        additionalProperties:
          $ref: '#/definitions/types.GameDefinition'
        type: object
    type: object
  types.GetAllUsersResponse:
    properties:
      users:
        additionalProperties:
          $ref: '#/definitions/types.User'
        type: object
    type: object
  types.GetGameByIDResponse:
    properties:
      game:
        $ref: '#/definitions/types.GameDefinition'
        type: object
    type: object
  types.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  types.RegisterResponse:
    properties:
      user:
        $ref: '#/definitions/types.User'
        type: object
    type: object
  types.ResponseGetUserByID:
    properties:
      user:
        $ref: '#/definitions/types.User'
        type: object
    type: object
  types.User:
    properties:
      username:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/games:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetAllGamesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      tags:
      - Games
  /api/games/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetGameByIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      tags:
      - Games
  /api/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: .
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      tags:
      - Auth
  /api/users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetAllUsersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      tags:
      - Users
  /api/users/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ResponseGetUserByID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      tags:
      - Users
swagger: "2.0"
