name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Server
      run: cd server && docker build . --file Dockerfile --tag mgogame:server_latest

#    - name: Build Client
#      run: cd client && docker build . --file Dockerfile --tag gogame:client_latest
