name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build server
      uses: docker/build-push-action@v1
      with:
        path: ./server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
        repository: maximeaubanel/gogame
        tags: server_latest

#    - name: Build client
#      uses: docker/build-push-action@v1
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        repository: maximeaubanel/gogame
#        tags: server_latest